# Generated by Django 4.2.4 on 2023-08-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoease', '0005_carrier_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
